ci:
    autofix_commit_msg: |
        style: pre-commit autofix
    autoupdate_commit_msg: |
        chore: pre-commit autoupdate

repos:
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-ast
    -   id: end-of-file-fixer
        exclude: ".yml$"
    -   id: trailing-whitespace
        exclude: ".yml$"
